#Hugo configuration
title = "sf"
baseURL = "https:\/\/saasdfdf.sadsdfsff.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
